name: $(Build.BuildId)
jobs:
  - job: buildFlux
    displayName: 'Build Flux'
    pool:
      vmImage: ubuntu-20.04
    container: adoptopenjdk:15-jdk-hotspot
    steps:
      - script: ./gradlew build
        displayName: 'Build'
      - task: PublishTestResults@2
        displayName: 'Publish Test Results'
        condition: succeededOrFailed()
